import React,{useState} from 'react';
export type LinkKey='indicator'|'activity'|'instrument'|'rubric'|'evidence';
export type Link={id:string;label:string;value:string;proposal:string};
export const defaults:Record<LinkKey,Link>={
 indicator:{id:'IND-01',label:'ตัวชี้วัด',value:'คะแนนความรู้หลังเรียน',proposal:'คุณภาพต้นแบบนวัตกรรมตามเกณฑ์ที่กำหนด'},
 activity:{id:'ACT-01',label:'กิจกรรม',value:'ฟังบรรยายและทำแบบทดสอบ',proposal:'วิเคราะห์ปัญหา ออกแบบต้นแบบ รับข้อเสนอแนะ และปรับปรุง'},
 instrument:{id:'INS-01',label:'เครื่องมือประเมิน',value:'แบบทดสอบความรู้',proposal:'แบบประเมินผลงานต้นแบบตามสภาพจริง'},
 rubric:{id:'RUB-01',label:'Rubric',value:'ยังไม่กำหนด',proposal:'พิจารณาความสอดคล้องกับปัญหา ความถูกต้อง ความเหมาะสม และความเป็นไปได้'},
 evidence:{id:'EVD-01',label:'หลักฐาน',value:'คะแนนแบบทดสอบ',proposal:'ต้นแบบ ฉบับก่อน–หลัง และบันทึกผลประเมิน'}};
const keys=Object.keys(defaults) as LinkKey[];
export function TraceabilityStudio({objective,onObjectiveChange,links,onLinksChange,history,onHistoryChange}:{objective:string;onObjectiveChange:(value:string)=>void;links:Record<LinkKey,Link>;onLinksChange:(value:Record<LinkKey,Link>)=>void;history:string[];onHistoryChange:(value:string[])=>void}){
 const [baseline,setBaseline]=useState(objective),[decisions,setDecisions]=useState<Partial<Record<LinkKey,'accepted'|'retained'>>>({}),[notes,setNotes]=useState<Partial<Record<LinkKey,string>>>({});
 const changed=objective.trim()!==baseline.trim();
 const confirm=()=>{setBaseline(objective);setDecisions({});onHistoryChange([...history,'ยืนยันฉบับวัตถุประสงค์: '+objective])};
 const apply=(key:LinkKey)=>{onLinksChange({...links,[key]:{...links[key],value:links[key].proposal}});setDecisions(d=>({...d,[key]:'accepted'}));onHistoryChange([...history,defaults[key].id+': รับข้อเสนอหลังตรวจทาน'])};
 return <section className="panel trace-studio"><span className="eyebrow">TRACEABILITY · SYNTHETIC DEMO</span><h2>ผลกระทบของการแก้วัตถุประสงค์</h2><p>การเปลี่ยนวัตถุประสงค์จะเปิดรายการให้ตรวจทาน โดยไม่เปลี่ยนองค์ประกอบอื่นโดยอัตโนมัติ ข้อเสนอเป็นตัวอย่างสำหรับฝึกคิด ไม่ใช่ข้อสรุปทางวิชาการ</p><p><strong>OBJ-01 · ฉบับอ้างอิง:</strong> {baseline}</p><label htmlFor="trace-objective">ฉบับที่กำลังแก้ไข</label><textarea id="trace-objective" rows={3} value={objective} onChange={e=>onObjectiveChange(e.target.value)}/>{changed?<div className="trace-alert" role="status"><strong>ตรวจพบการเปลี่ยนแปลง OBJ-01</strong><p>ตรวจความสอดคล้องของรายการที่เชื่อมโยงก่อนยืนยันฉบับใหม่</p></div>:<p>ยังไม่มีการเปลี่ยนแปลงจากฉบับอ้างอิงล่าสุด</p>}<div className="trace-grid">{keys.map(key=>{const x=links[key];return <article className="trace-item" key={x.id}><h3>{x.id} · {x.label}</h3><p><strong>ปัจจุบัน:</strong> {x.value}</p><p><strong>ข้อเสนอเพื่อพิจารณา:</strong> <mark className="revision-red">{x.proposal}</mark></p><label htmlFor={'trace-note-'+key}>เหตุผลประกอบการตัดสินใจ</label><textarea id={'trace-note-'+key} rows={2} value={notes[key]||''} onChange={e=>setNotes(n=>({...n,[key]:e.target.value}))}/><div className="trace-actions"><button disabled={!changed||!notes[key]?.trim()} onClick={()=>apply(key)}>ยอมรับข้อเสนอ</button><button disabled={!changed||!notes[key]?.trim()} onClick={()=>{setDecisions(d=>({...d,[key]:'retained'}));onHistoryChange([...history,x.id+': คงข้อความเดิมหลังตรวจทาน'])}}>คงข้อความเดิม</button></div><p className="trace-status">สถานะ: {decisions[key]==='accepted'?'รับข้อเสนอแล้ว':decisions[key]==='retained'?'คงข้อความเดิม':'รอตรวจทาน'}</p></article>})}</div><p>รายการที่พิจารณาแล้ว {keys.filter(k=>decisions[k]).length}/{keys.length} · การคงข้อความเดิมอาจเหมาะสมเมื่อองค์ประกอบนั้นยังรองรับวัตถุประสงค์อื่น</p><button disabled={!changed||!objective.trim()||keys.some(k=>!decisions[k])} onClick={confirm}>ยืนยันฉบับวัตถุประสงค์หลังตรวจผลกระทบ</button>{history.length>0&&<details><summary>ประวัติการตัดสินใจระหว่างเปิดหน้านี้ ({history.length})</summary><ol>{history.map((x,i)=><li key={i}>{x}</li>)}</ol></details>}<p className="lab-warning">ข้อมูลชั่วคราว ไม่บันทึกฐานข้อมูล ไม่ปรับผลการประเมินหรือหลักฐานย้อนหลัง และข้อมูลเชื่อมหน้าข้อเสนอและหน้าประเมินผลในหน่วยความจำเท่านั้น</p></section>}
